// constants/mockUsers.js
export const currentUser = {
  id: 1,
  username: "James (Myself)",
  avatarUrl: "https://via.placeholder.com/40",
  community: "UCC Community",
  dailyPoints: 150,
  weeklyPoints: 430,
  totalPoints: 1020,
  dailyEnergy: 2.5,
  weeklyEnergy: 18.3,
  monthlyEnergy: 71.6,
  rank: 5,
};

export const leaderboardUsers = [
  {
    id: 2,
    username: "Neighbor A",
    avatarUrl: "https://via.placeholder.com/40",
    dailyPoints: 200,
    weeklyPoints: 600,
    totalPoints: 1800,
  },
  {
    id: 3,
    username: "Neighbor B",
    avatarUrl: "https://via.placeholder.com/40",
    dailyPoints: 170,
    weeklyPoints: 520,
    totalPoints: 1500,
  },
  {
    id: 4,
    username: "Neighbor C",
    avatarUrl: "https://via.placeholder.com/40",
    dailyPoints: 160,
    weeklyPoints: 480,
    totalPoints: 1400,
  },
  {
    id: 5,
    username: "Neighbor D",
    avatarUrl: "https://via.placeholder.com/40",
    dailyPoints: 150,
    weeklyPoints: 460,
    totalPoints: 1350,
  },
  {
    id: 6,
    username: "Neighbor E",
    avatarUrl: "https://via.placeholder.com/40",
    dailyPoints: 140,
    weeklyPoints: 430,
    totalPoints: 1280,
  },
  {
    id: 7,
    username: "Neighbor F",
    avatarUrl: "https://via.placeholder.com/40",
    dailyPoints: 130,
    weeklyPoints: 410,
    totalPoints: 1200,
  },
  {
    id: 8,
    username: "Neighbor G",
    avatarUrl: "https://via.placeholder.com/40",
    dailyPoints: 120,
    weeklyPoints: 390,
    totalPoints: 1150,
  },
  {
    id: 9,
    username: "Neighbor H",
    avatarUrl: "https://via.placeholder.com/40",
    dailyPoints: 110,
    weeklyPoints: 360,
    totalPoints: 1080,
  },
  {
    id: 10,
    username: "Neighbor I",
    avatarUrl: "https://via.placeholder.com/40",
    dailyPoints: 100,
    weeklyPoints: 340,
    totalPoints: 1030,
  },
];

