// constants/mockUsers.js
export const currentUser = {
  id: 1,
  username: "James (Myself)",
  avatarUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  community: "UCC Community",
  dailyPoints: 150,
  weeklyPoints: 430,
  totalPoints: 1020,
  dailyEnergy: 2.5,
  weeklyEnergy: 18.3,
  monthlyEnergy: 71.6,
  rank: 5,
};

export const leaderboardUsers = [
  {
    id: 2,
    username: "Neighbor A",
    avatarUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    dailyPoints: 180,
    weeklyPoints: 520,
    totalPoints: 1600,
  },
  {
    id: 3,
    username: "Neighbor B",
    avatarUrl: "https://randomuser.me/api/portraits/women/2.jpg",
    dailyPoints: 210,
    weeklyPoints: 400,
    totalPoints: 1050,
  },
  {
    id: 4,
    username: "Neighbor C",
    avatarUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    dailyPoints: 130,
    weeklyPoints: 460,
    totalPoints: 1800,
  },
  {
    id: 5,
    username: "Neighbor D",
    avatarUrl: "https://randomuser.me/api/portraits/women/4.jpg",
    dailyPoints: 170,
    weeklyPoints: 610,
    totalPoints: 1300,
  },
  {
    id: 6,
    username: "Neighbor E",
    avatarUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    dailyPoints: 200,
    weeklyPoints: 480,
    totalPoints: 1100,
  },
  {
    id: 7,
    username: "Neighbor F",
    avatarUrl: "https://randomuser.me/api/portraits/women/6.jpg",
    dailyPoints: 120,
    weeklyPoints: 390,
    totalPoints: 1500,
  },
  {
    id: 8,
    username: "Neighbor G",
    avatarUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    dailyPoints: 160,
    weeklyPoints: 570,
    totalPoints: 1250,
  },
  {
    id: 9,
    username: "Neighbor H",
    avatarUrl: "https://randomuser.me/api/portraits/women/8.jpg",
    dailyPoints: 190,
    weeklyPoints: 430,
    totalPoints: 1000,
  },
  {
    id: 10,
    username: "Neighbor I",
    avatarUrl: "https://randomuser.me/api/portraits/men/9.jpg",
    dailyPoints: 140,
    weeklyPoints: 440,
    totalPoints: 1350,
  },
];
